# Generated by Django 4.2.7 on 2025-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("tutorial", "Tutorials"),
                    ("tech", "Tech Reviews"),
                    ("opinion", "Opinion Pieces"),
                ],
                default="tutorial",
                max_length=20,
            ),
        ),
    ]
