version: "3.8"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - DEBUG=${DEBUG:-True}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-your-secret-key-here}
            - DATABASE_URL=${DATABASE_URL:-sqlite:///db.sqlite3}
        depends_on:
            - db

    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=personal_website
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes:
    postgres_data:
