services:
    - type: web
      name: my-django-app
      runtime: python
      buildCommand: "chmod +x build.sh && ./build.sh"
      startCommand: "gunicorn personal_website.wsgi:application"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: my-django-db
                property: connectionString
          - key: DJANGO_SECRET_KEY
            generateValue: true
          - key: DEBUG
            value: "False"
          - key: DJANGO_SUPERUSER_USERNAME
            value: "shun_admin"
          - key: DJANGO_SUPERUSER_EMAIL
            value: "shawnmichael.sudaria04@gmail.com"
          - key: DJANGO_SUPERUSER_PASSWORD
            value: "N3tw0rkd0wn14!"
