# Generated by Django 5.2 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tutorial", "Tutorials"),
                            ("tech", "Tech Reviews"),
                            ("opinion", "Opinion Pieces"),
                        ],
                        default="tutorial",
                        max_length=20,
                    ),
                ),
                (
                    "markdown_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a Markdown (.md) file",
                        null=True,
                        upload_to="articles/markdown/",
                    ),
                ),
                ("content_md", models.TextField(editable=False)),
                ("content_html", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("technologies", models.CharField(max_length=200)),
                ("github_link", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("mobile", "Mobile Apps"),
                            ("ai", "AI/ML"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                ("pdf_file", models.FileField(upload_to="research_pdfs/")),
                ("published_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("technology", "Technology"),
                            ("engineering", "Engineering"),
                        ],
                        default="science",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Research",
                "ordering": ["-published_date"],
            },
        ),
    ]
