# Generated by Django 4.2.7 on 2025-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tutorial', 'Tutorials'), ('tech', 'Tech Reviews'), ('opinion', 'Opinion Pieces')], default='tutorial', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Apps'), ('ai', 'AI/ML')], default='web', max_length=20),
        ),
    ]
