# Generated by Django 4.2.7 on 2025-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_article_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markdown_file',
            field=models.FileField(blank=True, help_text='Upload a Markdown (.md) file', null=True, upload_to='articles/markdown/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_md',
            field=models.TextField(editable=False),
        ),
    ]
