# Generated by Django 4.2.7 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0002_remove_article_category_remove_project_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="carousel/")),
                ("title", models.CharField(blank=True, max_length=100)),
                ("caption", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
