# Generated by Django 4.2.7 on 2025-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Research'},
        ),
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True, help_text='Optional for ongoing research', null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='published_date',
            field=models.DateField(blank=True, help_text='Optional for ongoing research', null=True),
        ),
    ]
