# Generated by Django 5.2 on 2025-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0003_carouselimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                default="ongoing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="research",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
