# Generated by Django 4.2.7 on 2025-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_research_options_alter_research_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use current date/time', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use current date/time', null=True),
        ),
    ]
