# Generated by Django 5.2 on 2025-05-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0004_project_status_research_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="research",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="research_pdfs/"),
        ),
    ]
