# Generated by Django 4.2.7 on 2025-08-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_article_created_at_alter_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, help_text='Your website (optional)', null=True),
        ),
    ]
