# Generated by Django 4.2.7 on 2025-08-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', help_text='Brief description to show in article listing (max 500 characters)', max_length=500),
        ),
    ]
