# Generated by Django 4.2.7 on 2025-08-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accolade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the accolade (e.g., '2nd Runner Up, HackForGov Regionals 2023')", max_length=200)),
                ('description', models.TextField(help_text='Description of the achievement and competition details')),
                ('date_achieved', models.DateField(help_text='Date when this accolade was achieved')),
                ('organization', models.CharField(blank=True, help_text='Organization that hosted the competition (optional)', max_length=200)),
                ('position', models.CharField(blank=True, help_text="Position achieved (e.g., '2nd Runner Up', 'Finalist', 'Top 6')", max_length=100)),
                ('team_name', models.CharField(blank=True, help_text='Name of the team (if applicable)', max_length=100)),
                ('is_featured', models.BooleanField(default=True, help_text='Display this accolade on the home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accolade',
                'verbose_name_plural': 'Accolades',
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
    ]
