# Generated by Django 4.2.7 on 2025-08-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_accolade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or caption for the image', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the image')),
                ('image', models.ImageField(help_text='Upload the gallery image', upload_to='gallery/')),
                ('date_taken', models.DateField(blank=True, help_text='Date when the photo was taken (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text='Location where the photo was taken (optional)', max_length=200)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('travel', 'Travel'), ('events', 'Events'), ('nature', 'Nature'), ('urban', 'Urban'), ('people', 'People'), ('other', 'Other')], default='other', help_text='Category of the image', max_length=50)),
                ('is_featured', models.BooleanField(default=True, help_text='Display this image in the gallery')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
