# Generated by Django 4.2.7 on 2025-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Science"),
                    ("technology", "Technology"),
                    ("engineering", "Engineering"),
                    ("mathematics", "Mathematics"),
                ],
                default="science",
                max_length=20,
            ),
        ),
    ]
