# Generated by Django 4.2.7 on 2025-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Web Development"),
                    ("mobile", "Mobile Apps"),
                    ("ai", "AI/ML"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
